Controllers/questionController.cs
using KenderGartenFront.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace KenderGartenFront.Controllers
{
    public class questionController : Controller
    {
        // GET: question
        public ActionResult Index()
        {
            List<questionForum> getQuestion = new List<questionForum>();


            HttpClient Client = new HttpClient();
            Client.BaseAddress = new Uri("http://localhost:8085");
            Client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage response = Client.GetAsync("/api/question/").Result;
            IEnumerable<questionForum> result;
            if (response.IsSuccessStatusCode)
            {
                var ForumResponse = response.Content.ReadAsStringAsync().Result;

                //Deserializing the response recieved from web api and storing into the Employee list  

                result = JsonConvert.DeserializeObject<List<questionForum>>(ForumResponse);
            }
            else
            { result = null; }
            return View(result);
        }

        // GET: question/Details/5
        public ActionResult Details(int id)
        {
            HttpClient client = new HttpClient();
            questionForum question = null;
            client.BaseAddress = new Uri("http://localhost:8085");
            var responseTask = client.GetAsync("/api/question/" + id.ToString());

            var result = responseTask.Result;
            if (result.IsSuccessStatusCode)
            {
                var readTask = result.Content.ReadAsAsync<questionForum>();

                question = readTask.Result;
            }
            return View(question);
        }

        // GET: question/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: question/Create
        [HttpPost]
        public ActionResult Create(questionForum ques)
        {
           HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:8085");
            try 
            {

                // TODO: Add insert logic here
                client.PostAsJsonAsync<questionForum>("/api/question/",ques).ContinueWith((postTask) => postTask.Result.EnsureSuccessStatusCode());
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: question/Edit/5
        public ActionResult Edit(int id)
        {
            HttpClient client = new HttpClient();
            questionForum question = null;
            client.BaseAddress = new Uri("http://localhost:8085");
            var responseTask = client.GetAsync("/api/question/" + id.ToString());

            var result = responseTask.Result;
            if (result.IsSuccessStatusCode)
            {
                var readTask = result.Content.ReadAsAsync<questionForum>();

                question = readTask.Result;
            }
            return View(question);
        }

        // POST: question/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, questionForum ques)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:8085");
            //HTTP POST
            var putTask = client.PutAsJsonAsync<questionForum>("/api/question/" + id.ToString(), ques);
            putTask.Wait();
            var result = putTask.Result;
            if (result.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: question/Delete/5
        public ActionResult Delete(int id)
        {
            HttpClient client = new HttpClient();
            questionForum question = null;
            client.BaseAddress = new Uri("http://localhost:8085");
            var responseTask = client.GetAsync("/api/question/" + id.ToString());

            var result = responseTask.Result;
            if (result.IsSuccessStatusCode)
            {
                var readTask = result.Content.ReadAsAsync<questionForum>();

                question = readTask.Result;
            }
            return View(question);
        }

        // POST: question/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                HttpClient Client = new HttpClient();
                Client.BaseAddress = new Uri("http://localhost:8085");
                HttpResponseMessage response = Client.DeleteAsync("/api/question/" + id.ToString()).Result;

                return RedirectToAction("Index");
            }
            catch
            {
                return View();

            }
        }
    }
}

Controllers/reponseController.cs
using KenderGartenFront.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace KenderGartenFront.Controllers
{
    public class reponseController : Controller
    {
        // GET: reponse
        public ActionResult Index()
        {

            List<reponseForum> getForum = new List<reponseForum>();


            HttpClient Client = new HttpClient();
            Client.BaseAddress = new Uri("http://localhost:8085");
            Client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage response = Client.GetAsync("/api/reponse/").Result;
            IEnumerable<reponseForum> result;
            if (response.IsSuccessStatusCode)
            {
                var ForumResponse = response.Content.ReadAsStringAsync().Result;

                //Deserializing the response recieved from web api and storing into the Employee list  

                result = JsonConvert.DeserializeObject<List<reponseForum>>(ForumResponse);
            }
            else
            { result = null; }
            return View(result);
        }

        // GET: reponse/Details/5
        public ActionResult Details(int id)
        {
            HttpClient client = new HttpClient();
            reponseForum rep = null;
            client.BaseAddress = new Uri("http://localhost:8085");
            var responseTask = client.GetAsync("/api/reponse/" + id.ToString());

            var result = responseTask.Result;
            if (result.IsSuccessStatusCode)
            {
                var readTask = result.Content.ReadAsAsync<reponseForum>();

                rep = readTask.Result;
            }
            return View(rep);
        }

        // GET: reponse/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: reponse/Create
        [HttpPost]
        public ActionResult Create(reponseForum rep,int id)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:8085");
            try
            {

                // TODO: Add insert logic here
                client.PostAsJsonAsync<reponseForum>("/api/reponse/add/" + id.ToString(), rep).ContinueWith((postTask) => postTask.Result.EnsureSuccessStatusCode());
                return RedirectToAction("Index","question");
            }
            catch
            {
                return View();
            }
        }

        // GET: reponse/Edit/5
        public ActionResult Edit(int id)
        {
            HttpClient client = new HttpClient();
            reponseForum rep = null;
            client.BaseAddress = new Uri("http://localhost:8085");
            var responseTask = client.GetAsync("/api/reponse/" + id.ToString());

            var result = responseTask.Result;
            if (result.IsSuccessStatusCode)
            {
                var readTask = result.Content.ReadAsAsync<reponseForum>();

                rep = readTask.Result;
            }
            return View(rep);
        }

        // POST: reponse/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, reponseForum reps)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:8085");
            //HTTP POST
            var putTask = client.PutAsJsonAsync<reponseForum>("/api/reponse/" + id.ToString(), reps);
            putTask.Wait();
            var result = putTask.Result;
            if (result.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: reponse/Delete/5
        public ActionResult Delete(int id)
        {
            HttpClient client = new HttpClient();
           reponseForum rep = null;
            client.BaseAddress = new Uri("http://localhost:8085");
            var responseTask = client.GetAsync("/api/reponse/" + id.ToString());

            var result = responseTask.Result;
            if (result.IsSuccessStatusCode)
            {
                var readTask = result.Content.ReadAsAsync<reponseForum>();

                rep = readTask.Result;
            }
            return View(rep);
        }

        // POST: reponse/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                HttpClient Client = new HttpClient();
                Client.BaseAddress = new Uri("http://localhost:8085");
                HttpResponseMessage response = Client.DeleteAsync("/api/reponse/delete/" + id.ToString()).Result;

                return RedirectToAction("Index");
            }
            catch
            {
                return View();

            }
        }





















    }
}

Views/question/Create.cshtml
@model KenderGartenFront.Models.questionForum

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>questionForum</h4>
            @Html.ActionLink("List of questions", "Index","question")

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.question, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.question, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.question, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/question/Delete.cshtml
@model KenderGartenFront.Models.questionForum

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>questionForum</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.question)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.question)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/question/Details.cshtml
@model KenderGartenFront.Models.questionForum

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>questionForum</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.question)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.question)
        </dd>

    </dl>
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

@Html.ActionLink("Create response", "Create", "reponse", new { id = Model.id}, null)
<table class="table">
    <tr>

        <th>
            @Html.DisplayNameFor(model => model.reponses)
        </th>
        <th> Action</th>


    </tr>

    @foreach (var item in Model.reponses)
    {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.reponse)

            </td>

            <td>

            </td>

        </tr>
    }

</table>

Views/question/Edit.cshtml
@model KenderGartenFront.Models.questionForum

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>questionForum</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.question, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.question, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.question, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/question/Index.cshtml
@model IEnumerable<KenderGartenFront.Models.questionForum>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<p>
    @Html.ActionLink("List Response", "Index","reponse")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.question)
        </th>

        <th> Action</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.question)
            </td>

            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.id }) |
                @Html.ActionLink("Details", "Details", new { id = item.id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>