Models/Forum.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace KenderGartenFront.Models
{
    public class Forum
    { public int id { get; set; }
        public string title { get; set; }
        public string subject { get; set; }
        public string date { get; set; }
        public  IList<questionForum> questions { get; set; }

    }
}

Controllers/ForumController.cs
using KenderGartenFront.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Web.Mvc;
using Newtonsoft.Json;
using System.Threading.Tasks;

namespace KenderGartenFront.Controllers
{
    public class ForumController : Controller
    {
        // GET: Forum
        public ActionResult Index()
        {
            List<Forum> getForum = new List<Forum>();


            HttpClient Client = new HttpClient();
            Client.BaseAddress = new Uri("http://localhost:8085");
            Client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage response = Client.GetAsync("/api/forum/").Result;
            IEnumerable<Forum> result;
            if (response.IsSuccessStatusCode)
            {
                var ForumResponse = response.Content.ReadAsStringAsync().Result;

                //Deserializing the response recieved from web api and storing into the Employee list  

                result = JsonConvert.DeserializeObject<List<Forum>>(ForumResponse);
            }
            else
            { result = null; }
            return View(result);
        }

        // GET: Forum/Details/5
        public ActionResult Details(int id)
        {
            int counts=0;
            HttpClient client = new HttpClient();
            Forum forum = null;
            client.BaseAddress = new Uri("http://localhost:8085");
            //HTTP GET("SpringMVC/servlet/GetActivities")
            var responseTask = client.GetAsync("/api/forum/" + id.ToString());
            var responseTask2 = client.GetAsync("/api/forum/getlikes/" + id.ToString());
            var results = responseTask2.Result;
            var result = responseTask.Result;
            if (results.IsSuccessStatusCode)
            {
                var readTasks = results.Content.ReadAsAsync<int>();

                counts = readTasks.Result;
                ViewBag.countLike = counts;
            }


            if (result.IsSuccessStatusCode)
            {
                var readTask = result.Content.ReadAsAsync<Forum>();

                forum = readTask.Result;
            }
            return View(forum);
        }

        // GET: Forum/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Forum/Create
        [HttpPost]
        public object Create(Forum forum)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:8085");
            try
            {
                // TODO: Add insert logic here
                client.PostAsJsonAsync<Forum>("/api/forum/", forum).ContinueWith((postTask) => postTask.Result.EnsureSuccessStatusCode());
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Forum/Edit/5
        public ActionResult Edit(int id)
        {
            HttpClient client = new HttpClient();
            Forum forum = null;
            client.BaseAddress = new Uri("http://localhost:8085");
            var responseTask = client.GetAsync("/api/forum/" + id.ToString());

            var result = responseTask.Result;
            if (result.IsSuccessStatusCode)
            {
                var readTask = result.Content.ReadAsAsync<Forum>();

                forum = readTask.Result;
            }
            return View(forum);
        }

        // POST: Forum/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Forum f)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:8085");
            //HTTP POST
            var putTask = client.PutAsJsonAsync<Forum>("/api/forum/" + id.ToString(), f);
            putTask.Wait();
            var result = putTask.Result;
            if (result.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: Forum/Delete/5
        public ActionResult Delete(int id)
        {
            HttpClient client = new HttpClient();
            Forum forum = null;
            client.BaseAddress = new Uri("http://localhost:8085");
            var responseTask = client.GetAsync("/api/forum/" + id.ToString());

            var result = responseTask.Result;
            if (result.IsSuccessStatusCode)
            {
                var readTask = result.Content.ReadAsAsync<Forum>();

                forum = readTask.Result;
            }
            return View(forum);
        }

        // POST: Forum/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                HttpClient Client = new HttpClient();
                Client.BaseAddress = new Uri("http://localhost:8085");
                HttpResponseMessage response = Client.DeleteAsync("/api/forum/" + id.ToString()).Result;

                return RedirectToAction("Index");
            }
            catch
            {
                return View();

            }
        }

        public object Likes(likes forum, int id)
        {
            HttpClient client = new HttpClient();
            Forum fs = null;
            client.BaseAddress = new Uri("http://localhost:8085");
            //HTTP GET("SpringMVC/servlet/GetActivities")
            var responseTask = client.GetAsync("/api/forum/" + id.ToString());

            var result = responseTask.Result;
            if (result.IsSuccessStatusCode)
            {
                var readTask = result.Content.ReadAsAsync<Forum>();

                fs = readTask.Result;
            }


            try
            {
                // TODO: Add insert logic here
                forum.forum_id = id;
                client.PostAsJsonAsync<likes>("/api/forum/likes", forum).ContinueWith((postTask) => postTask.Result.EnsureSuccessStatusCode());

               





                return RedirectToAction("Index");
            }
            catch
            {
                return View(fs);
            }
        }











    }
}

Controllers/questionController.cs
using KenderGartenFront.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace KenderGartenFront.Controllers
{
    public class questionController : Controller
    {
        // GET: question
        public ActionResult Index()
        {
            List<questionForum> getQuestion = new List<questionForum>();


            HttpClient Client = new HttpClient();
            Client.BaseAddress = new Uri("http://localhost:8085");
            Client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
            HttpResponseMessage response = Client.GetAsync("/api/question/").Result;
            IEnumerable<questionForum> result;
            if (response.IsSuccessStatusCode)
            {
                var ForumResponse = response.Content.ReadAsStringAsync().Result;

                //Deserializing the response recieved from web api and storing into the Employee list  

                result = JsonConvert.DeserializeObject<List<questionForum>>(ForumResponse);
            }
            else
            { result = null; }
            return View(result);
        }

        // GET: question/Details/5
        public ActionResult Details(int id)
        {
            HttpClient client = new HttpClient();
            questionForum question = null;
            client.BaseAddress = new Uri("http://localhost:8085");
            var responseTask = client.GetAsync("/api/question/" + id.ToString());

            var result = responseTask.Result;
            if (result.IsSuccessStatusCode)
            {
                var readTask = result.Content.ReadAsAsync<questionForum>();

                question = readTask.Result;
            }
            return View(question);
        }

        // GET: question/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: question/Create
        [HttpPost]
        public ActionResult Create(questionForum ques)
        {
           HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:8085");
            try 
            {

                // TODO: Add insert logic here
                client.PostAsJsonAsync<questionForum>("/api/question/",ques).ContinueWith((postTask) => postTask.Result.EnsureSuccessStatusCode());
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: question/Edit/5
        public ActionResult Edit(int id)
        {
            HttpClient client = new HttpClient();
            questionForum question = null;
            client.BaseAddress = new Uri("http://localhost:8085");
            var responseTask = client.GetAsync("/api/question/" + id.ToString());

            var result = responseTask.Result;
            if (result.IsSuccessStatusCode)
            {
                var readTask = result.Content.ReadAsAsync<questionForum>();

                question = readTask.Result;
            }
            return View(question);
        }

        // POST: question/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, questionForum ques)
        {
            HttpClient client = new HttpClient();
            client.BaseAddress = new Uri("http://localhost:8085");
            //HTTP POST
            var putTask = client.PutAsJsonAsync<questionForum>("/api/question/" + id.ToString(), ques);
            putTask.Wait();
            var result = putTask.Result;
            if (result.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: question/Delete/5
        public ActionResult Delete(int id)
        {
            HttpClient client = new HttpClient();
            questionForum question = null;
            client.BaseAddress = new Uri("http://localhost:8085");
            var responseTask = client.GetAsync("/api/question/" + id.ToString());

            var result = responseTask.Result;
            if (result.IsSuccessStatusCode)
            {
                var readTask = result.Content.ReadAsAsync<questionForum>();

                question = readTask.Result;
            }
            return View(question);
        }

        // POST: question/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                HttpClient Client = new HttpClient();
                Client.BaseAddress = new Uri("http://localhost:8085");
                HttpResponseMessage response = Client.DeleteAsync("/api/question/" + id.ToString()).Result;

                return RedirectToAction("Index");
            }
            catch
            {
                return View();

            }
        }
    }
}

Views/Forum/Create.cshtml
@model KenderGartenFront.Models.Forum

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Forum</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Forum/Delete.cshtml
@model KenderGartenFront.Models.Forum

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Forum</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.subject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/Forum/Details.cshtml
@model KenderGartenFront.Models.Forum

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<h3> Nombre de Like :  
    @ViewBag.countLike
    </h3>

<div>
    <h4>Forum</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.subject)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.subject)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
    @Html.ActionLink("Like", "Likes", new { id = Model.id })

</p>

Views/Forum/Edit.cshtml
@model KenderGartenFront.Models.Forum

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Forum</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.subject, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Forum/Index.cshtml
@model IEnumerable<KenderGartenFront.Models.Forum>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
    @Html.ActionLink("List of questions", "Index","question")

</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.subject)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.date)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.subject)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.date)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>